version: '3.8'

services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'stockman'
      MYSQL_ROOT_PASSWORD: 'rootpass'
    ports:
      - '3307:3306'
    volumes:
      - /stockman:/var/lib/mysql