spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockman
    username: root
    password: maselko-sql
  liquibase:
    contexts: prod

jws:
  sharedKey: wsc7e4lk-a23a-4vdb-brgc-33d4g0c58261