spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockman
    username: root
    password: rootpass
  liquibase:
    contexts: prod
    change-log: classpath:db/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: validate

jws:
  sharedKey: wsc7e4lk-a23a-4vdb-brgc-33d4g0c58261
  expirationSecond: 86400 # 24*60*60